# Generated by Django 4.1.1 on 2022-09-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0002_auto_20220413_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='aac',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='additem',
            name='desc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='additem',
            name='gw',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='additem',
            name='plno',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='additem',
            name='relatedplno',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='additem',
            name='specno',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='additem',
            name='unifiedplno',
            field=models.CharField(max_length=120),
        ),
    ]
